//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSLab.User
{
    using TSLab.Script;
    using TSLab.Script.Handlers;


    public sealed class Script : System.IDisposable
    {
        
        public Script()
        {
        }
        
        public void Execute(IContext context, ISecurity Symbol)
        {
            // =================================================
            // Handlers
            // =================================================
            // =================================================
            // Trading
            // =================================================
            int barsCount = Symbol.Bars.Count;
            if ((context.IsLastBarUsed == false))
            {
                barsCount--;
            }
            for (int i = 0; (i < barsCount); i++)
            {
            }
        }
        
        public void Dispose()
        {
        }
    }
}
