//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TSLab.User
{
    using System;
    using TSLab.Script;
    using TSLab.Utils;


    public sealed class Script : System.IDisposable
    {

        private TSLab.Script.Handlers.Close Close_h = new TSLab.Script.Handlers.Close();

        public Script()
        {
        }

        public void Execute(TSLab.Script.Handlers.IContext context, TSLab.Script.ISecurity Symbol)
        {
            // =================================================
            // Graph & Canvas Panes
            // =================================================
            // Make 'MainChart' pane
            TSLab.Script.IGraphPane MainChart_pane = context.CreateGraphPane("MainChart", null);
            MainChart_pane.Visible = true;
            MainChart_pane.HideLegend = false;
            // Initialize 'Close' item
            this.Close_h.Context = context;
            // Make 'Close' item data
            System.Collections.Generic.IList<double> Close = context.GetData("Close", new string[] {
                "Symbol"
            }, delegate {
                return this.Close_h.Execute(Symbol);

            });
            // =================================================
            // Handlers
            // =================================================
            // =================================================
            // Trading
            // =================================================
            int barsCount = Symbol.Bars.Count;
            if ((context.IsLastBarUsed == false))
            {
                barsCount--;
            }
            for (int i = 0; (i < barsCount); i++)
            {
            }
            if (context.IsOptimization)
            {
                return;
            }
            // =================================================
            // Charts
            // =================================================
            // Make 'Symbol' chart
            TSLab.Script.IGraphList MainChart_pane_Symbol_chart = MainChart_pane.AddList("MainChart_pane_Symbol_chart", ("Symbol"
                            + (" ["
                            + (Symbol.Symbol + "]"))), Symbol, TSLab.Script.CandleStyles.BAR_CANDLE, TSLab.Script.CandleFillStyle.Decreasing, true, -15197697, TSLab.Script.PaneSides.RIGHT);
            Symbol.ConnectSecurityList(MainChart_pane_Symbol_chart);
            MainChart_pane_Symbol_chart.AlternativeColor = -53451;
            MainChart_pane_Symbol_chart.Autoscaling = true;
            MainChart_pane.UpdatePrecision(TSLab.Script.PaneSides.RIGHT, Symbol.Decimals);
        }

        public void Dispose()
        {
        }
    }
}
